spring:
  application:
    name: aggregator

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.yandex.practicum.telemetry.serializer.AvroSerializer

